import Foundation

// ─────────────────────────────────────────────────────────
// Candidate — a single action candidate from the search system
//
// Protected backbone per ARCHITECTURE_RULES.md.
//
// Each candidate bundles a hypothesis (why this action should
// work), the action schema to execute, and a source tag
// describing how it was generated (memory, graph, or LLM
// fallback). The SearchController generates multiple
// candidates per state, executes them, and selects the best.
// ─────────────────────────────────────────────────────────

/// How the candidate was generated.
public enum CandidateSource: String {
    /// Suggested by StateMemoryIndex based on historical success.
    case memory
    /// Derived from a PlanningGraphEngine edge.
    case graph
    /// Generated by the LLM as a fallback when memory and graph
    /// have no suggestions.
    case llmFallback = "llm_fallback"
}

/// A single action candidate produced during the search phase.
public struct Candidate: Identifiable {

    public let id: String
    /// Free-text hypothesis explaining why this action should succeed.
    public let hypothesis: String
    /// The action schema to execute.
    public let schema: ActionSchema
    /// How this candidate was generated.
    public let source: CandidateSource

    public init(
        id: String = UUID().uuidString,
        hypothesis: String,
        schema: ActionSchema,
        source: CandidateSource
    ) {
        self.id = id
        self.hypothesis = hypothesis
        self.schema = schema
        self.source = source
    }
}
